POST http://localhost:5000/api/v1/products/add
Content-Type: application/json

{
    "label":"Ordinateur Dell Optiplex i7 Laptop",
    "brand":"Sony",
    "description":"Screen diamond",
    "price":4250.123
}